services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
      - REDIS_URI=redis:6379
      - PORT=8000
      - MONGO_DB_NAME=event-trigger

  mongodb:
    image: mongo:latest
    container_name: eventtrigger-db
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: eventtrigger-redis
    restart: always
    ports:
      - "6379:6379"
