databases:
  - name: mongodb
    type: mongodb
    version: 4.4
    plan: free
    runtime: docker

  - name: redis
    type: redis
    version: 6
    plan: free
    runtime: docker

services:
  - name: backend
    type: web
    runtime: docker
    dockerfile: ./Dockerfile
    envVars:
      - key: MONGO_URI
        value: mongodb://mongodb:27017/mydb
      - key: REDIS_URI
        value: redis:6379
      - key: PORT
        value: 8000
      - key: MONGO_DB_NAME
        value: event-trigger
    env: docker
    plan: free
    autoDeploy: false
